# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: pygments

# Title
name: GovConnect
subtitle: An Agile Workplace Initiative

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/govconnect'

# Author/Organization info to be displayed in the templates
author:
  name: GovConnect Team
  url: mailto:18f-govconnect@gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: assets/img/logo.png
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: What is GovConnect?
  url: index.html
  internal: true
- text: Get Started
  url: intro.html
  internal: true
- text: 1. Create a Vision
  url: vision.html
  internal: true
- text: 2. Assemble a Team
  url: team.html
  internal: true
- text: 3. Leverage Technology
  url: technology.html
  internal: true
- text: 4. Create Projects
  url: projects.html
  internal: true
- text: 5. Get the Word Out
  url: marketing.html
  internal: true
- text: 6. Measure Success
  url: metrics.html
  internal: true
- text: History of GovConnect
  url: history.html
  internal: true
- text: Workshop Summary
  url: workshop.html
  internal: true
# - text: Research
#   url: research.html
#   internal: true

# - text: DOCter Repo
#   url: https://github.com/cfpb/DOCter
#   internal: false

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: GovConnect
  description: an Agile Workforce Initiative
  url: https://github.com/18F/govconnect

# Style Variables

brand_color: "#1E6D54"       # "#09295c"
